name: Test and release when tagged

on: [push]

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        environment:
          - test-py312
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: ${{ matrix.environment }}
      - run: pixi run --environment ${{ matrix.environment }} pytest

